### ISSUE TITLE
✈️ Pilot March 8

### ISSUE THREAD

**Issue by JamesPHoughton** [willschulz/bad-influence#5]

**Comment by xehu** [comment]
Thoughts after discussion with Rachel and Sophie:
- **Participant Recruitment:** We should likely expand beyond the initial WBL individuals that we pre-surveyed. Sophie mentioned that Marketing 101 students tend to be more active after Spring Break.
- **Scheduling: ** It will be scheduled similar to an in-person study (e.g., with slots that people commit to), but can be taken from anywhere (remotely)
- **# of Participants: ** No upper limit, as many as we can get?
- **James and Tech Support: ** We should provide contact information for James (or another individual familiar with the tech side of the platform, perhaps on James' team) during the pilots so that individuals can contact with questions or tech issues

**Comment by JamesPHoughton** [comment]
- [ ] we should preview the bell "ding" during the intro screen and tell people that it corresponds to a new stage.
- [ ] put in the intro steps "if you have problems, here's the feedback button"
- [ ] "Earn the base HIT reward" in the login page is too specific to MTurk and wont make sense in this context.


Scheduling
- Trying to do small group of 18 to start with (scale up slowly to minimize risk)
- Will recruit more than 18 as there will be some attrition
- Then do two larger groups if all goes to plan
- Ready to start week of March 13
- Probably don't want to do the two-part study, just run straight through without an explicit launch time.

**Comment by RachelAbigail** [comment]
**Suggestions:** 
- Give a preview of "switch" ding in the study intro (e.g., "when it's time to transition between discussion questions, you will here the following sound...")
- Remove line on intro screen that says "earn base HIT reward" -- this won't make sense for WBL group
- It looks like participants can still skip the topic-specific post-survey questions -- need to make these required 

**Notes:**
- WBL will send us a new study details form to complete
- WBL will schedule sessions, probably starting the week of March 20. 
- WBL will schedule 3 sessions (session 1: ~18 people, session 2: ~39 people, session 3: ~39 people)
- We need to send WBL a list of people to pay (including their WBL participant ID) after the study

**Comment by RachelAbigail** [comment]
@JamesPHoughton open check box tasks complete?

**Comment by JamesPHoughton** [comment]
Todo items moved to issues in the appropriate projects.
